"""update user profile

Revision ID: 10301c011049
Revises: 646efa9a484b
Create Date: 2026-04-02 14:33:11.617550

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '10301c011049'
down_revision = '646efa9a484b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('next_appointment', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('provider_notes', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('barriers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'barriers')
    op.drop_column('profiles', 'provider_notes')
    op.drop_column('profiles', 'next_appointment')
    op.create_table('providers',
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('is_first_login', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=1)
    op.create_table('preferences',
    sa.Column('user_email', sa.VARCHAR(), nullable=False),
    sa.Column('dietary_restrictions', sa.VARCHAR(), nullable=True),
    sa.Column('cuisines', sa.VARCHAR(), nullable=True),
    sa.Column('meal_types', sa.VARCHAR(), nullable=True),
    sa.Column('cooking_skills', sa.VARCHAR(), nullable=True),
    sa.Column('cooking_methods', sa.VARCHAR(), nullable=True),
    sa.Column('kitchen_equipment', sa.VARCHAR(), nullable=True),
    sa.Column('weekly_budget', sa.VARCHAR(), nullable=True),
    sa.Column('food_programs', sa.VARCHAR(), nullable=True),
    sa.Column('grocery_locations', sa.VARCHAR(), nullable=True),
    sa.Column('internet_access', sa.VARCHAR(), nullable=True),
    sa.Column('tech_devices', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_index(op.f('ix_preferences_user_email'), 'preferences', ['user_email'], unique=False)
    op.create_table('grocery_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('qty', sa.FLOAT(), nullable=True),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('is_purchased', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_items_user_email'), 'grocery_items', ['user_email'], unique=False)
    op.create_index(op.f('ix_grocery_items_id'), 'grocery_items', ['id'], unique=False)
    # ### end Alembic commands ###