"""add badges

Revision ID: 371d41fe35f7
Revises: 646efa9a484b
Create Date: 2026-04-02 15:16:24.319300

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '371d41fe35f7'
down_revision = '646efa9a484b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['badge_name'], ['badges.name'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'badge_name', name='unique_user_badge')
    )
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_email'), 'user_badges', ['user_email'], unique=False)
    op.drop_index(op.f('ix_grocery_items_id'), table_name='grocery_items')
    op.drop_index(op.f('ix_grocery_items_user_email'), table_name='grocery_items')
    op.drop_table('grocery_items')
    op.drop_index(op.f('ix_preferences_user_email'), table_name='preferences')
    op.drop_table('preferences')
    op.add_column('profiles', sa.Column('weight_goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider_email')
    op.drop_column('users', 'name')
    op.drop_column('profiles', 'weight_goal')
    op.create_table('preferences',
    sa.Column('user_email', sa.VARCHAR(), nullable=False),
    sa.Column('dietary_restrictions', sa.VARCHAR(), nullable=True),
    sa.Column('cuisines', sa.VARCHAR(), nullable=True),
    sa.Column('meal_types', sa.VARCHAR(), nullable=True),
    sa.Column('cooking_skills', sa.VARCHAR(), nullable=True),
    sa.Column('cooking_methods', sa.VARCHAR(), nullable=True),
    sa.Column('kitchen_equipment', sa.VARCHAR(), nullable=True),
    sa.Column('weekly_budget', sa.VARCHAR(), nullable=True),
    sa.Column('food_programs', sa.VARCHAR(), nullable=True),
    sa.Column('grocery_locations', sa.VARCHAR(), nullable=True),
    sa.Column('internet_access', sa.VARCHAR(), nullable=True),
    sa.Column('tech_devices', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_index(op.f('ix_preferences_user_email'), 'preferences', ['user_email'], unique=False)
    op.create_table('grocery_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('qty', sa.FLOAT(), nullable=True),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('is_purchased', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_items_user_email'), 'grocery_items', ['user_email'], unique=False)
    op.create_index(op.f('ix_grocery_items_id'), 'grocery_items', ['id'], unique=False)
    op.drop_index(op.f('ix_user_badges_user_email'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###